name: Run Python Telegram Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (adjust as needed)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent hanging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install python-telegram-bot==20.6 apscheduler==3.10.1 python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Verify file permissions
      run: |
        chmod +x Rahul 
        ls -l Rahul  # Verify permissions

    - name: Run bot with error handling
      run: |
        if [ ! -f raja.py ]; then
          echo "❌ Error: raja.py not found!"
          exit 1
        fi
        
        echo "🔄 Starting bot..."
        python raja.py || echo "❌ Bot crashed with exit code $?"
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        # Add other required secrets:
        ADMIN_ID: ${{ secrets.ADMIN_ID }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: bot-logs
        path: |
          *.log
          logs/
